apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-bender
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-bender
  template:
    metadata:
      labels:
        app: hello-bender
    spec:
      containers:
        - name: hello-bender
          image: bygui86/hello-bender:v1.0.0
          imagePullPolicy: Always
          ports:
          - name: web
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-bender
  labels:
    app: hello-bender
spec:
  selector:
    app: hello-bender
  ports:
  - name: web
    port: 8080
    targetPort: web
