apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-fry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-fry
  template:
    metadata:
      labels:
        app: hello-fry
    spec:
      containers:
        - name: hello-fry
          image: bygui86/hello-fry:v1.0.0
          imagePullPolicy: Always
          ports:
          - name: web
            containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-fry
  labels:
    app: hello-fry
spec:
  selector:
    app: hello-fry
  ports:
  - name: web
    port: 8080
    targetPort: web
