apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 15
  
  # serviceAccountName: default
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  
  containers:
    - name: busybox
      # buildroot
      image: busybox:1.36.1-uclibc
      # alpine
      # image: busybox:1.36.1-musl
      # debian
      # image: busybox:1.36.1-glibc
      imagePullPolicy: Always
      command:
        - "sleep 3600"
        # - ./usr/local/bin/scripts/curl-inf-loop.sh
        # - ./usr/local/bin/scripts/ip-checker.bash
      # env:
      #   # curl-inf-loop
      #   - name: HOST
      #     value: # Type here
      #   - name: PORT
      #     value: # Type here
      #   - name: ENDPOINT
      #     value: # Type here
      #   # ip-checker
      #   - name: HTTP_CHECK_URL
      #     value: # Type here
      #   - name: K8S_NODE_NAME
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: spec.nodeName
      #   - name: K8S_NODE_IP
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: status.hostIP
      #   - name: K8S_POD_NAME
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: metadata.name
      #   - name: K8S_POD_IP
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: status.podIP
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: curl-inf-loop
          mountPath: /usr/local/bin/scripts/curl-inf-loop.sh
          subPath: curl-inf-loop.sh
        - name: ip-checker
          mountPath: /usr/local/bin/scripts/ip-checker.bash
          subPath: ip-checker.bash

  volumes:
    - name: curl-inf-loop
      configMap:
        name: curl-inf-loop
    - name: ip-checker
      configMap:
        name: ip-checker

  # nodeSelector:
  #   kubernetes.io/os: linux

  # tolerations:
  #   - operator: Exists
  #     effect: NoSchedule
  #   - key: dedicated
  #     operator: Equal
  #     value: # Type here
  #     effect: NoSchedule

  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: dedicated
  #               operator: In
  #               values:
  #                 - # Type here
