apiVersion: v1
kind: Pod
metadata:
  name: gcloud
  labels:
    app: gcloud
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 5
  
  containers:
    - name: gcloud
      image: gcr.io/google.com/cloudsdktool/cloud-sdk:471.0.0-alpine
      # image: gcr.io/google.com/cloudsdktool/cloud-sdk:471.0.0-slim
      imagePullPolicy: Always
      command:
        - sleep
        - "3600"
      # args:
      #   - # Type here
      # env:
      #   - name: KEY
      #     value: value
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 100m
          memory: 256Mi
