apiVersion: v1
kind: Pod
metadata:
  name: storage-filler
  labels:
    app: storage-filler
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 15
  
  containers:
    - name: busybox
      # buildroot
      image: busybox:1.36.1-uclibc
      # alpine
      # image: busybox:1.36.1-musl
      # debian
      # image: busybox:1.36.1-glibc
      imagePullPolicy: Always
      command:
        # - sleep
        # - "3600"
        - /usr/local/bin/scripts/storage-filler.sh
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 32Mi
      volumeMounts:
        - name: storage-filler
          mountPath: /usr/local/bin/scripts/storage-filler.sh
          subPath: storage-filler.sh
          readOnly: false
        - name: data
          mountPath: /usr/local/bin/data

  volumes:
    - name: storage-filler
      configMap:
        name: storage-filler
        defaultMode: 0777
    - name: data
      persistentVolumeClaim:
        claimName: storage-filler
