apiVersion: v1
kind: Pod
metadata:
  name: k8s-army-knife
  labels:
    app: k8s-army-knife
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 15
  
  serviceAccountName: kubectl-view
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  
  containers:
    - name: k8s-army-knife
      image: bygui86/k8s-army-knife:0.0.1
      imagePullPolicy: Always
      command:
        - sleep
        - "3600"
      # args:
      #   - # Type here
      # env:
      #   - name: KEY
      #     value: value
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 256Mi
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
