apiVersion: v1
kind: Pod
metadata:
  name: debian
  labels:
    app: debian
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 5

  containers:
    - name: debian
      image: debian:12.5-slim
      imagePullPolicy: Always
      command:
        - sleep
        - "3600"
      # args:
      #   - # Type here
      # env:
      #   - name: KEY
      #     value: value
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
