apiVersion: v1
kind: Pod
metadata:
  name: busybox
  labels:
    app: busybox
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 15

  containers:
    - name: busybox
      # buildroot
      image: busybox:1.36.1-uclibc
      # alpine
      # image: busybox:1.36.1-musl
      # debian
      # image: busybox:1.36.1-glibc
      imagePullPolicy: Always
      command:
        - sleep
        - "3600"
      # args:
      #   - # Type here
      # env:
      #   - name: KEY
      #     value: value
      # ports:
      #   - name: # Type here
      #     containerPort: # Type here
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
      # livenessProbe:
      #   httpGet:
      #     path: # Type here
      #     port: # Type here
      #   initialDelaySeconds: # Type here
      #   periodSeconds: # Type here
      #   timeoutSeconds: # Type here
      #   successThreshold: 1
      #   failureThreshold: 3
      # readinessProbe:
      #   httpGet:
      #     path: # Type here
      #     port: # Type here
      #   initialDelaySeconds: # Type here
      #   periodSeconds: # Type here
      #   timeoutSeconds: # Type here
      #   successThreshold: 1
      #   failureThreshold: 3
      # volumeMounts:
      #   - name: config
      #     mountPath: /usr/bin/config
      #   - name: secret
      #     mountPath: /usr/bin/config/ # Type here
      #     subPath: # Type here
      #   - name: temp-data
      #     mountPath: /tmp
      #   - name: persistent-data
      #     mountPath: /usr/bin/data

  # volumes:
  #   - name: config
  #     configMap:
  #       name: # Type here
  #   - name: secret
  #     secret:
  #       secretName: # Type here
  #   - name: temp-data
  #     emptyDir: {}
  #   - name: persistent-data
  #     persistentVolumeClaim:
  #       claimName: # Type here

  # nodeSelector:
  #   kubernetes.io/os: linux

  # tolerations:
  #   - operator: Exists
  #     effect: NoSchedule
  #   - key: dedicated
  #     operator: Equal
  #     value: # Type here
  #     effect: NoSchedule

  # affinity:
  #   nodeAffinity:
  #     requiredDuringSchedulingIgnoredDuringExecution:
  #       nodeSelectorTerms:
  #         - matchExpressions:
  #             - key: dedicated
  #               operator: In
  #               values:
  #                 - # Type here
