apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-hashicorp
  labels:
    app: echo-hashicorp
    domain: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-hashicorp
  template:
    metadata:
      labels:
        app: echo-hashicorp
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: echo-hashicorp
          image: hashicorp/http-echo:1.0
          imagePullPolicy: Always
          args:
            - -text="hello world"
            # - -listen=:8080
          ports:
            - name: http
              containerPort: 5678
              # containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
