apiVersion: v1
kind: Pod
metadata:
  name: echo-hashicorp
  labels:
    app: echo-hashicorp
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 5

  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001

  containers:
    - name: echo-hashicorp
      image: hashicorp/http-echo:1.0
      imagePullPolicy: Always
      args:
        - -text="hello world"
        # - -listen=:8080
      ports:
        - name: http
          containerPort: 5678
          # containerPort: 8080
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
