apiVersion: v1
kind: Pod
metadata:
  name: tcp-pinger
  labels:
    app: tcp-pinger
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 5
  
  containers:
    - name: netshoot
      image: nicolaka/netshoot:v0.12
      imagePullPolicy: Always
      command:
        # - sleep
        # - "3600"
        - /usr/local/bin/scripts/tcp-pinger.sh
      env:
        - name: HOST
          value: tcp-listener.svc
        - name: PORT
          value: "8600"
      resources:
        requests:
          cpu: 50m
          memory: 32Mi
        limits:
          cpu: 50m
          memory: 32Mi
      volumeMounts:
        - name: tcp-pinger
          mountPath: /usr/local/bin/scripts/tcp-pinger.sh
          subPath: tcp-pinger.sh

  volumes:
    - name: tcp-pinger
      configMap:
        name: tcp-pinger
        defaultMode: 0777
