apiVersion: v1
kind: Pod
metadata:
  name: stress-resources
  labels:
    app: stress-resources
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 5
  
  containers:
    - name: k8s-army-knife
      image: bygui86/k8s-army-knife:1.1.0
      imagePullPolicy: Always
      command:
        # - sleep
        # - "3600"
        - sh
        - -c
        # CPU - stress 1 CPU core for 1h
        # - "stress -c 1 --timeout 3600"
        # MEM - stress the memory with 10 workers each of size 128M for 1h
        # - "stress --vm 10 --vm-bytes 128M --timeout 3600"
        # CPU + MEM - stress 1 CPU core and the memory with 10 workers each of size 128M for 1h
        - "stress -c 1 --vm 10 --vm-bytes 128M --timeout 3600"
      resources:
        requests:
          cpu: 2
          memory: 1G
        limits:
          cpu: 2
          memory: 2G
