apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: logs-checker
spec:
  # storageClassName: standard-csi-expandable
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
