apiVersion: v1
kind: ServiceAccount
metadata:
  name: logs-checker

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logs-checker
rules:
  - apiGroups:
    - ""
    resources:
    - pods
    - pods/log
    verbs:
    - get
    - watch
    - list

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logs-checker
roleRef:
  kind: ClusterRole
  name: logs-checker
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: logs-checker
    namespace: default
