apiVersion: v1
kind: Pod
metadata:
  name: kubectl
  labels:
    app: kubectl
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 5
  
  serviceAccountName: kubectl-view
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  
  containers:
    - name: kubectl
      # bygui86
      image: bygui86/kubectl:v1.29.3
      # image: bygui86/kubectl:v1.28.8
      # codefresh
      # image: quay.io/codefresh/kubectl:1.29.2
      # image: quay.io/codefresh/kubectl:1.28.4
      # rancher
      # image: rancher/kubectl:1.29.2
      # image: rancher/kubectl:1.28.7
      imagePullPolicy: Always
      command:
        - sleep
        - "3600"
      # args:
      #   - # Type here
      # env:
      #   - name: KEY
      #     value: value
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
