apiVersion: v1
kind: Pod
metadata:
  name: netshoot
  labels:
    app: netshoot
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 5

  containers:
    - name: netshoot
      image: nicolaka/netshoot:v0.12
      imagePullPolicy: Always
      command:
        - sleep
        - "3600"
      # args:
      #   - # Type here
      # env:
      #   - name: KEY
      #     value: value
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
