apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
  labels:
    app: ubuntu
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 15

  containers:
    - name: ubuntu
      image: ubuntu:24.04
      imagePullPolicy: Always
      command:
        - sleep
        - "3600"
      # args:
      #   - # Type here
      # env:
      #   - name: KEY
      #     value: value
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
