apiVersion: v1
kind: Pod
metadata:
  name: git-sync
  labels:
    app: git-sync
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 5

  initContainers:
    - name: git-sync-init
      image: registry.k8s.io/git-sync/git-sync:v3.6.5
      imagePullPolicy: Always
      envFrom:
        - secretRef:
            name: git-sync
      env:
        - name: GIT_SYNC_ONE_TIME
          value: "true"
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
      volumeMounts:
        - name: repo
          mountPath: /usr/local/bin/repo/
        - name: tmp
          mountPath: /tmp

  containers:
    - name: busybox
      # buildroot
      image: busybox:1.36.1-uclibc
      # alpine
      # image: busybox:1.36.1-musl
      # debian
      # image: busybox:1.36.1-glibc
      imagePullPolicy: Always
      command:
        - sleep
        - "3600"
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
      volumeMounts:
        - name: repo
          mountPath: /usr/local/bin/repo/
    - name: git-sync
      image: registry.k8s.io/git-sync/git-sync:v3.6.5
      imagePullPolicy: Always
      envFrom:
        - secretRef:
            name: git-sync
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
      volumeMounts:
        - name: repo
          mountPath: /usr/local/bin/repo/
        - name: tmp
          mountPath: /tmp

  volumes:
    - name: repo
      emptyDir: {}
    - name: tmp
      emptyDir: {}
