apiVersion: v1
kind: Secret
metadata:
  name: git-sync
stringData:
  # See https://github.com/kubernetes/git-sync#manual
  GIT_SYNC_REPO: https://github.com/bygui86/kubectl
  GIT_SYNC_BRANCH: main
  # GIT_SYNC_USERNAME: # type here
  # GIT_SYNC_PASSWORD: # type here
  # GIT_SYNC_ROOT default /git
  GIT_SYNC_ROOT: /usr/local/bin/repo/
  # WARN: "GIT_SYNC_LINK" will replace "GIT_SYNC_DEST" in git-sync v4
  GIT_SYNC_LINK: repo
  GIT_SYNC_DEST: repo
  GIT_SYNC_REV: HEAD
  GIT_SYNC_DEPTH: "1"
  GIT_SYNC_PERIOD: 180s
  GIT_SYNC_SYNC_TIMEOUT: "120"
  GIT_SYNC_MAX_FAILURES: "3"
  GIT_SYNC_ADD_USER: "true"
  GIT_SYNC_KNOWN_HOSTS: "false"
