apiVersion: v1
kind: Pod
metadata:
  name: script-executor
  labels:
    app: script-executor
    domain: tools
spec:
  restartPolicy: Never
  terminationGracePeriodSeconds: 5
  
  securityContext:
    runAsNonRoot: true
    runAsUser: 1001
    runAsGroup: 1001
    fsGroup: 1001
  
  containers:
    - name: ubuntu
      image: ubuntu:24.04
      imagePullPolicy: Always
      command:
        - sleep
        - "3600"
        # - ./usr/local/bin/scripts/slim-shady.bash
        # - ./usr/local/bin/scripts/curl-inf-loop.sh
      # env:
      #   # curl-inf-loop
      #   - name: HOST
      #     value: # Type here
      #   - name: PORT
      #     value: # Type here
      #   - name: ENDPOINT
      #     value: # Type here
      #   # ip-checker
      #   - name: HTTP_CHECK_URL
      #     value: # Type here
      #   - name: K8S_NODE_NAME
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: spec.nodeName
      #   - name: K8S_NODE_IP
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: status.hostIP
      #   - name: K8S_POD_NAME
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: metadata.name
      #   - name: K8S_POD_IP
      #     valueFrom:
      #       fieldRef:
      #         fieldPath: status.podIP
      resources:
        requests:
          cpu: 100m
          memory: 64Mi
        limits:
          cpu: 100m
          memory: 64Mi
      securityContext:
        privileged: false
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
      volumeMounts:
        - name: slim-shady
          mountPath: /usr/local/bin/scripts/slim-shady.bash
          subPath: slim-shady.bash
          readOnly: false
        - name: curl-inf-loop
          mountPath: /usr/local/bin/scripts/curl-inf-loop.sh
          subPath: curl-inf-loop.sh
          readOnly: false

  volumes:
    - name: slim-shady
      configMap:
        name: slim-shady
        defaultMode: 0500
    - name: curl-inf-loop
      configMap:
        name: curl-inf-loop
        defaultMode: 0500
