apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-server
  labels:
    app: http-server
    domain: tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: http-server
  template:
    metadata:
      labels:
        app: http-server
    spec:
      terminationGracePeriodSeconds: 15
      containers:
        - name: http-server
          image: bygui86/http-server:v1.0.0
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: http-server
          ports:
            - name: http
              containerPort: 8080
            - name: metrics
              containerPort: 9090
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 64Mi
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          #   successThreshold: 1
          #   failureThreshold: 3
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          #   timeoutSeconds: 3
          #   successThreshold: 1
          #   failureThreshold: 3
