apiVersion: v1
kind: Service
metadata:
  name: http-client
spec:
  selector:
    app: http-client
  ports:
    - name: http
      port: 8080
      targetPort: http
    - name: metrics
      port: 9090
      targetPort: metrics
